services:
  toniai-bot:
    build: .
    container_name: toniai_bot
    restart: unless-stopped
    stop_grace_period: 60s
    network_mode: host
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./data:/app/data